/*
 Quantcast measurement tag
 Copyright (c) 2008-2022, Quantcast Corp.
*/
'use strict';(function(e,t,q){var u=function(a){var c=q.createElement("a");c.href=a;return c},v=[/^http[s]?:\/\/((adservice.google.*)|([^\/]*fls\.doubleclick\.net))\/.*~oref=(?<url>[^;\n]*)/,/^http[s]?:\/\/[^\/]*tealium.*\/.*page_url=(?<url>[^&]*)/],w=function(a){return a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")},x=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},y=function(a,c,f){return a?"nc"===a?!c||!f||0>c.indexOf(f):"eq"===a?c===f:"sw"===a?0===c.indexOf(f):
"ew"===a?(a=c.length-f.length,c=c.lastIndexOf(f,a),-1!==c&&c===a):"c"===a?0<=c.indexOf(f):!1:!1},b=function(a,c,f){if(t.top!==t.self){try{for(var d=0;d<v.length;d++){var m=q.location.href.match(v[d]);if(m&&m.groups.url){var g=decodeURIComponent(m.groups.url);break}}}catch(r){}g=g?u(g):u(q.referrer)}else g=q.location;g=g.href;y(c,g,f)?a(g):a(!1)},k=function(a,c,f){c=document.getElementsByTagName("meta");for(var d,m,g=[],r=0;r<c.length;r++)if(d=c[r],m=d.getAttribute("name")||d.getAttribute("property"),
m==f){m=g;g=m.concat;var h=f;if(d=d.getAttribute("content")){var p=h;p=-1!==p.toLowerCase().indexOf("tag")||-1!==p.toLowerCase().indexOf("keyword")||0===p.toLowerCase().indexOf("qc:");-1===h.toLowerCase().indexOf("tag")&&-1===h.toLowerCase().indexOf("keyword")&&0===h.toLowerCase().indexOf("qc:")||(d=d.replace(/\.+/g," "));if(p)for(h=d.split(","),d=0;d<h.length;d++)h[d]=w(h[d]);else h=w(d.replace(/,+/g," "))}else h=d;g=g.call(m,h)}0<g.length?a(g):a(!1)},n=function(a){return"array"===x(a)?{labels:a.join(",")}:
{labels:""+a}},l=function(a,c){var f=[],d;if("array"===x(c)){for(d=0;d<c.length;d++)f.push(a+"."+c[d]);return{labels:f.join(",")}}return{labels:a+"."+c}};__qc.apply(null,["rules",[e,null,[[l,"Indiewire.category"]],[[k,"exactmatch","category"],[b,"c","indiewire"]]],[e,null,[[l,"Indiewire.topics"]],[[k,"exactmatch","topics"],[b,"c","indiewire"]]],[e,null,[[l,"Indiewire.tags"]],[[k,"exactmatch","tags"],[b,"c","indiewire"]]],[e,null,[[l,"WWD.topics"]],[[k,"exactmatch","topics"],[b,"c","wwd"]]],[e,null,
[[l,"WWD.tags"]],[[k,"exactmatch","tags"],[b,"c","wwd"]]],[e,null,[[l,"Footwearnews.topics"]],[[k,"exactmatch","topics"],[b,"c","footwearnews"]]],[e,null,[[n,"Variety.section.film"]],[[b,"c","variety"],[b,"c","/film"]]],[e,null,[[n,"Variety.section.music"]],[[b,"c","variety"],[b,"c","/music"]]],[e,null,[[n,"Variety.section.tech"]],[[b,"c","variety"],[b,"c","/digital"]]],[e,null,[[l,"RollingStone.titles"]],[[k,"exactmatch","cXenseParse:title"],[b,"c","rollingstone"]]],[e,null,[[l,"RollingStone.authors"]],
[[k,"exactmatch","cXenseParse:author"],[b,"c","rollingstone"]]],[e,null,[[l,"RollingStone.categories"]],[[k,"exactmatch","cXenseParse:pmc-category"],[b,"c","rollingstone"]]],[e,null,[[l,"RollingStone.tags"]],[[k,"exactmatch","cXenseParse:pmc-tag"],[b,"c","rollingstone"]]],[e,null,[[l,"Variety.titles"]],[[k,"exactmatch","og:title"],[b,"c","variety"]]],[e,null,[[n,"Variety.section.tv"]],[[b,"c","variety"],[b,"c","/tv"]]],[e,null,[[n,"Variety.section.global"]],[[b,"c","variety"],[b,"c","/global"]]],
[e,null,[[n,"Variety.section.video"]],[[b,"c","variety"],[b,"c","/videos"]]],[e,null,[[n,"Variety.section.video"]],[[b,"c","variety"],[b,"c","/video"]]]])})("p-31f3D02tYU8zY",window,document);